<a href="https://colab.research.google.com/github/leofgonzalez/Rainfall-Prediction-Project/blob/main/Data_Scraping_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Scraping Project**

This project has the intention of demonstrating the basic web-scraping functionality using the library BeautifulSoup in an example with static attributes (website prepared for this goal) for guaranteeing the continuous functionality of the code in the future.

Let's start installing BeautifulSoup

In [1]:
!pip3 install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.4.1)

# Importing required libraries

In [2]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

# The Data Source

The website chosen for this project was Books to Scrape, you can access it here https://books.toscrape.com/

We'll be looking for the following information about the Books:

- Book Name
- Rating
- Image
- Price

In [5]:
for i in range(1,51):

  url = f"https://books.toscrape.com/catalogue/page-{i}.html"

  response = requests.get(url) # Requesting the information from the website

  response = response.content # Attributing the content to the variable

  soup = BeautifulSoup(response,'html.parser') # Using BeautifulSoup to transform the binary data to HTML

  ol = soup.find('ol') # Finding the Order List / Main group point in the HTML structure to the products (Books)

  articles = ol.find_all('article', class_='product_pod') # Finding each product (Book) in the Order List, each one will have the complete information about each product


# I'll create a list to receive all the information on each product

  books = []

# Each article is organized with the complete information of each product
# Now I'm going to loop into each article and gather the information seeked

  for article in articles:
    image = article.find('img')
    title = image.attrs['alt']
    star = article.find('p')
    price = article.find('p', class_='price_color').text

    star = star['class'][1] # Data Cleaning
    price = float(price[1:]) # Data Cleaning and transformation to numerical content

    books.append([title, price, star])

# Transforming the data to CSV - Pandas

In [9]:
df = pd.DataFrame(books, columns=['Title','Price','Star Rating'])

df.to_csv('books.csv')

df

                                                Title  Price Star Rating
0                                        Frankenstein  38.00         Two
1                    Forever Rockers (The Rocker #12)  28.80       Three
2                         Fighting Fate (Fighting #6)  39.24       Three
3                                                Emma  32.93         Two
4                                     Eat, Pray, Love  51.32       Three
5                     Deep Under (Walker Security #1)  47.09        Five
6   Choosing Our Religion: The Spiritual Lives of ...  28.42        Four
7   Charlie and the Chocolate Factory (Charlie Buc...  22.85       Three
8           Charity's Cross (Charles Towne Belles #4)  41.24         One
9                                        Bright Lines  39.07        Five
10           Bridget Jones's Diary (Bridget Jones #1)  29.82         One
11                      Bounty (Colorado Mountain #7)  37.26        Four
12               Blood Defense (Samantha Brinkman #1)  20.30       Three
13  Bleach, Vol. 1: Strawberry and the Soul Reaper...  34.65        Five
14                               Beyond Good and Evil  43.38         One
15  Alice in Wonderland (Alice's Adventures in Won...  55.53         One
16   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  57.06        Four
17  A Spy's Devotion (The Regency Spies of London #1)  16.97        Five
18                1st to Die (Women's Murder Club #1)  53.98         One
19                 1,000 Places to See Before You Die  26.08        Five